### ISSUE TITLE
monitors/DAG

### ISSUE THREAD

**Issue by quattrinia** [revbayes/revbayes.github.io#17]
Hi there, I am trying to run this tutorial
https://revbayes.github.io/tutorials/clocks/
And, I have it all working up until the very end. 
When I type the 
monitors[1]=mnModel(filename="/data/mcfadden/aquattrini/ANALYSIS/Paramuricea/revbayes/output/mcmc.log", printgen=100) 
   Error:	Workspace objects cannot be used inside DAG's! You tried to access the DAG node of type 'RevObject'.

Any advice?

**Comment by wadedismukes** [comment]
Hello,

This tutorial appears to be a bit outdated. Apologies for that!

Try replacing these lines:
```
monitors[1] = mnModel(filename="output/TimetTree_bears_mcmc.log", printgen=10)

monitors[2] = mnFile(filename="output/TimeTree_bears_mcmc.trees",
printgen=10, timetree)

monitors[3] = mnScreen(printgen=10, root_time, tmrca_Ursidae)
```
with these lines:
```
monitors.append(mnModel(filename="output/TimetTree_bears_mcmc.log",
printgen=10))

monitors.append(mnFile(filename="output/TimeTree_bears_mcmc.trees",
printgen=10, timetree))

monitors.append(mnScreen(printgen=10, root_time, tmrca_Ursidae))
```
Hope this helps!

Wade


On Tue, Feb 9, 2021 at 10:36 AM quattrinia <notifications@github.com> wrote:
>
> Hi there, I am trying to run this tutorial
> https://revbayes.github.io/tutorials/clocks/
> And, I have it all working up until the very end.
> When I type the
> monitors[1]=mnModel(filename="/data/mcfadden/aquattrini/ANALYSIS/Paramuricea/revbayes/output/mcmc.log", printgen=100)
> Error: Workspace objects cannot be used inside DAG's! You tried to access the DAG node of type 'RevObject'.
>
> Any advice?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
-------------------------------------------
Wade Dismukes
EEB PhD candidate | Heath Lab
Iowa State University | EEOB

**Comment by quattrinia** [comment]
Thanks. These all seemed to work, but then I got this error upon adding
mymcmc = mcmc(mymodel, monitors, moves)

   Error:	Unable to connect monitor to DAG copy because variable name was lost

here is my entire code:
D <- readDiscreteCharacterData(file="/data/mcfadden/aquattrini/ANALYSIS/Paramuricea/parajan21.nex")
n_sites <- D.nchar()
mi = 1
source("/data/mcfadden/aquattrini/ANALYSIS/Paramuricea/revbayes/scripts/m_BDP.Rev")
source("/data/mcfadden/aquattrini/ANALYSIS/Paramuricea/revbayes/scripts/uncl.Rev")
mymodel=model(er)
monitors.append(mnModel(filename="/data/mcfadden/aquattrini/ANALYSIS/Paramuricea/revbayes/output/mcmc.log", printgen=100))
monitors.append(mnFile(filename="/data/mcfadden/aquattrini/ANALYSIS/Paramuricea/revbayes/output/mcmc.trees", printgen=100, timetree))
monitors.append(mnScreen(printgen=100, root_time, tmrca_clav))
mymcmc = mcmc(mymodel, monitors, moves)
mymcmc.burnin(generations=5000,tuningInterval=100)
mymcmc.run(generations=25000)

**Comment by Imsolaris** [comment]
I seem to have similar error but out of the moves 
I was trying to use this tutorial:https://revbayes.github.io/tutorials/ctmc/

br_len_lambda=10
psi := dnUniformTopologyBranchLength(taxa,branchLengthDistribution=dnExponential(br_len_lambda))
   Error:	Workspace objects cannot be used inside DAG's! You tried to access the DAG node of type 'RevObject'.
